# If you come from bash you might have to change your $PATH.

autoload -U compinit
compinit

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export UPDATE_ZSH_DAYS=14

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
if [ -e ${ZSH}/themes/powerlevel10k ]; then
    ZSH_THEME="powerlevel10k/powerlevel10k"
else
    ZSH_THEME="agnoster"
    DEFAULT_USER="${USER}@${HOST}"
fi

COMPLETION_WAITING_DOTS="true"

# CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
[[ ! -f ~/.fzf.zsh ]] && bindkey "OA" history-beginning-search-backward
[[ ! -f ~/.fzf.zsh ]] && bindkey "OB" history-beginning-search-forward

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git vi-mode colorize)
ZSH_COLORIZE_STYLE="colorful"

source $ZSH/oh-my-zsh.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"
alias lt='ls -Alrt'

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Some trigger external plugins
[[ -f ~/init.zsh ]] && source ~/init.zsh

# Following lines are generated automatically by some program, feel free to remove them
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX="Yes"
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
